#
#
#  Copyright © Greazi 2020 | All Rights Reserved.
#  Unauthorized copying of this file, via any medium is strictly prohibited.
#  Proprietary and confidential.
#  Written by Greazi
#
#



#
#  MagicValley-Plugin configuration
#  Last updated on ${project.version}-b${buildNumber}
#
#####

#
#  Settings for MVpl in general
###
General:
    Locale: en_US
    MOTD_Enabled: true
    EventBroadcasts: true
    EventInfoOnPlayerJoin: true
    AdminNotifications: true
#
#  Settings for Backups
#  Allow mcMMO to create zip backups for config files and flatfile data on shutdown.
###
Backups:
    Enabled: true

    Keep:
        Last_24_Hours: true
        Daily_Last_Week: true
        Weekly_Past_Months: true

#
#  Settings for commands
###
Commands:
    mcmmo:
        Donate_Message: true
