# ------------------------------------------------------------------------------------------------------------------- #
# TODO change this to the plugin name                                                                                 #
#             __  ___                       ____                              ____  __            _                   #
#            /  |/  /___ __   _____  ____  / __ )____ _________              / __ \/ /_  ______ _(_)___               #
#           / /|_/ / __ `/ | / / _ \/ __ \/ __  / __ `/ ___/ _ \   ______   / /_/ / / / / / __ `/ / __ \              #
#          / /  / / /_/ /| |/ /  __/ / / / /_/ / /_/ (__  )  __/  /_____/  / ____/ / /_/ / /_/ / / / / /              #
#         /_/  /_/\__,_/ |___/\___/_/ /_/_____/\__,_/____/\___/           /_/   /_/\__,_/\__, /_/_/ /_/               #
#                                                                                       /____/                        #
#                               MavenBase-Plugin - config.yml - Configuration.                                        #
#                               Copyright 2020 Greazi_Times | All rights reserved.                                    #
#                                   (Generated by MagicValley-Plugin 0.1.8)                                           #
#                                                                                                                     #
# ------------------------------------------------------------------------------------------------------------------- #
#                                                                                                                     #
#  How MavenBase-Plugin works:                                                                                        #
#                                                                                                                     #
#  MavenBase-Plugin has a lot of features: CommandSPY,                                                                #
#     - CommandSPY analyse player behaviour and records two things.                                                   #
#       Command usage and chat log. Some command may be false reports or logs.                                        #
#     -                                                                                                               #
#     -                                                                                                               #
#                                                                                                                     #
#                                                                                                                     #
#                                                                                                                     #
#                                                                                                                     #
#                                                                                                                     #
#                                                                                                                     #
# ------------------------------------------------------------------------------------------------------------------- #


# ------------------------------------------------------------------------------------------------------------------- #
#                                               ___ _     _          _                                                #
#                                              / __| |___| |__  __ _| |                                               #
#                                             | (_ | / _ \ '_ \/ _` | |                                               #
#                                              \___|_\___/_.__/\__,_|_|                                               #
#                                                                                                                     #
# ------------------------------------------------------------------------------------------------------------------- #
# TODO add all global settings

