#
#
#  Copyright © Greazi 2020 | All Rights Reserved.
#  Unauthorized copying of this file, via any medium is strictly prohibited.
#  Proprietary and confidential.
#  Written by Greazi
#
#  
name: MVpl
version: ${project.version}
build: ${buildNumber}
description: >
  MagicValleyPlugin (For short MVPL), is a custom made plugin for MagicValley.
  The goal of this plugin is to take MagicValley to the next level.
  Notice:
  There will be updates everytime we have a positive commit, these commits will be tested and imported into the plugin if these are stable.

author: Greazi
website: https://www.magicvalley.nl/plugin
main: me.greazi.magicvalley.MVpl

commands:
  ### Main command ###
  mvpl:
    description: Shows a brief mod description
    permission: mvpl.commands.mvpl

  ### Reload local ###
  mvplreloadlocale:
    aliases: [mvreloadlocale]
    description: Reloads locale
    permission: mvpl.commands.reloadlocale

  ### Test command ###
  mvtest:
    description: The test command to test new commands
    permission: mvpl.commands.test

permissions:
  ##################################
  #            Clusters            #
  ##################################
  ### Default ###
  mvpl.default:
    default: true
    description: The permission cluster for the default players
    children:
      ## Default permissions
      mvpl.commands.mvpl: true

  ### Magician ###
  mvpl.magician:
    default: false
    description: The permission cluster for the rank Magician
    children:
      ## previous cluster
      mvpl.default: true
      ## Magician permissions

  ### Staff ###
  mvpl.staff:
    default: false
    description: The permission cluster for staff members
    children:
      ## previous cluster
      mvpl.magicvain: true
      ## staff permissions
      mvpl.commands.models: true

      
  ### All permissions ###
  mvpl.*:
    default: false
    description: The permission cluster to give all the permissions
    children:
      ## previous cluster
      mvpl.staff: true
      ## Admin permissions
      mvpl.commands.reloadlocale: true
      mvpl.commands.test: true

  ##################################
  #            Commands            #
  ##################################

  ### Default ###
  mvpl.commands.mvpl:
    default: false
    description: The permission to use the main command /mvpl

  ### Staff ###
  mvpl.commands.models:
    default: false
    description: The permission to use /md or /model or /models

  ### Admin ###
  mvpl.commands.reloadlocale:
    default: false
    description: The command to reload the language file
  mvpl.commands.test:
    default: false
    description: To use the test command that contains a possible new command

  ##################################
  #             Bypass             #
  ##################################
