#
#
#  Copyright © Greazi 2020 | All Rights Reserved.
#  Unauthorized copying of this file, via any medium is strictly prohibited.
#  Proprietary and confidential.
#  Written by Greazi
#
#
# !-----------------------------------------------------------------------------------------------!
#                         Welcome to the main configuration of MVpl
# !-----------------------------------------------------------------------------------------------!
#
#           This is the main configuration file of MVpl. All the settings are inside here
#
#   MagicValley-Plugin configuration
#   Last updated on 1.1.149-Snapshot-b46
#
#
#
#
#
#
#
#
#


#

#
#####

#
#  Settings for MVpl in general
###
General:
    Locale: en_US
    MOTD_Enabled: true
    EventBroadcasts: true
    EventInfoOnPlayerJoin: true
    AdminNotifications: true
#
#  Settings for Backups
#  Allow mcMMO to create zip backups for config files and flatfile data on shutdown.
###
Backups:
    Enabled: true

    Keep:
        Last_24_Hours: true
        Daily_Last_Week: true
        Weekly_Past_Months: true

#
#  Settings for commands
###
Commands:
    mcmmo:
        Donate_Message: true

##################################################
################# Do Not Touch ###################
##################################################
ConfigVersion: 1.1.149
