#
#  MagicValley-Plugin configuration
#  Last updated on 1.1.149-Snapshot-b44
#
#####

#
#  Settings for MVpl in general
###
General:
    Locale: en_US
    MOTD_Enabled: true
    EventBroadcasts: true
    EventInfoOnPlayerJoin: true
    AdminNotifications: true
#
#  Settings for Backups
#  Allow mcMMO to create zip backups for config files and flatfile data on shutdown.
###
Backups:
    Enabled: true

    Keep:
        Last_24_Hours: true
        Daily_Last_Week: true
        Weekly_Past_Months: true

#
#  Settings for commands
###
Commands:
    mcmmo:
        Donate_Message: true
